# Generated by Django 5.2.11 on 2026-03-02 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='institutes.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
                'unique_together': {('institute', 'employee_id')},
            },
        ),
    ]
