# Generated by Django 5.2.11 on 2026-03-02 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=15)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institutes.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roll_number'],
                'unique_together': {('institute', 'roll_number')},
            },
        ),
    ]
